openapi: 3.0.1
info:
  title: Intent for mNCC
  version: 1.0.0
  description: >-
    OAS 3.0.1 definition for a new intentExpectation for meta Network Cluster Controller
paths: {}
components:
  schemas:
    Intent-mncc:
      description: >-
        This set of intents represent the possible request to the mncc.
      allOf:
        - $ref : "TS28312_IntentNrm.yaml#/components/schemas/Intent-Single"
        - type: object
          properties:
            userLabel:
              type: string
            intentExpectations:
              description: >-
                     Expectations for all the mncc adaptors
              type: array
              items:
                # type: object
                oneOf:
                  - $ref: "IntentExpectation_L2SM.yaml#/components/schemas/NewNetworkExpectation"
                  - $ref: "IntentExpectation_5GCMC.yaml#/components/schemas/New5GFlowExpectation"
                  # - $ref: "IntentExpectation_L2SM.yaml#/components/schemas/L2SMExpectations"
                  # - $ref: "IntentExpectation_5GCMC.yaml#/components/schemas/5GCMCExpectations"
                  # - $ref: "TS28312_IntentNrm.yaml#/components/schemas/IntentExpectation"       
            intentContexts:
              type: array
              items:
                oneOf:
                  - $ref : "IntentExpectation_L2SM.yaml#/components/schemas/L2SMIntentContext"
                  - $ref : "IntentExpectation_5GCMC.yaml#/components/schemas/5GCMCIntentContext"
              description: >-
                It describes the list of Context(s) in mNCC which represents the constraints and conditions that should apply 
                for the entire intent even if there may be specific contexts defined for specific parts of the intent 