openapi: 3.0.1
info:
  title: Intent for network management
  version: 1.0.0
  description: >-
    OAS 3.0.1 Definition for intents in the network domain
paths: {}
components:
  schemas:
    Intent-nrmg:
      description: >-
        This set of intents represent the possible request to the network.
      oneOf:
        - $ref: "IntentMncc.yaml#/components/schemas/Intent-mncc"
    Slice-request:
      description: >-
        This set of intents represent the possible request to the network.
      oneOf: 
        - $ref: "IntentSlice.yaml#/components/schemas/Intent-slice"