openapi: 3.0.1
info:
  title: Intent for network management
  version: 1.0.0
  description: >-
    OAS 3.0.1 Definition for intents in the network domain
paths: {}
components:
  schemas:
    Intent-nrmg:
      description: >-
        This set of intents represent the possible request to the network.
      type: object
      properties:
        Intent:  
          oneOf:
            - $ref: "IntentMncc.yaml#/components/schemas/Intent-mncc"
            - $ref: "IntentBSSF.yaml#/components/schemas/Intent-bssf"
            - $ref : "TS28312_IntentNrm.yaml#/components/schemas/Intent-Single"